version: '3.8'

services:
  keycloak:
    build: .
    ports:
      - '8080:8080'
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
    depends_on:
      - keycloak-db
    volumes:
      - keycloak-data:/opt/keycloak/data

  keycloak-db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  keycloak-data:
  postgres-data:
